### ISSUE TITLE
Question regarding other methods

### ISSUE THREAD

**Issue by Jackysi** [selim13/laravel-mix-compress#40]
Hello. First of thanks for this great plugin. Saves time compressing stuff on fly!

I was wondering... How could we also trigger compression to brotli/gzip on .copy method, or minify or others like it?
For example, I have a simple js already minified copying to directory, I would just like to compress it after copy is complete. Is that possible?

E.g.:
` .copy( 'resources/js/libs/prism.js', 'public/assets/js/prism.min.js' )`

**Comment by selim13** [comment]
Hello!
I don't think it is possible since copy/combine/minify tasks don't pass files through the webpack (and this extension relies on compression-webpack-plugin).

One need to write a separate compression task which works directly on provided files, e.g. `mix.copy('src/app.js', 'dist/app.js').compressFiles(['dist/app.js']);`. But I don't think that I will be implementing this soon, as I don't actively use laravel-mix right now.

As a quick and dirty solution, you can run compression from you package.json build script, something like this: `"build": "mix --production && gzip --keep public/assets/js/prism.min.js`

**Comment by Jackysi** [comment]
I see! I was reading the code a little and I did figure that it requires a file to go through webpack.  So it makes all sense! 

It is good idea to combine build commands yeah. I was just hoping there is built-in solution as mix is super easy :). I did notice there is also Vite / Rollup Mix out, so at some point I will be changing to that. But thank you very much for your answer and the plugin!!!
