### ISSUE TITLE
TypeError: Cannot read property 'tapPromise' of undefined

### ISSUE THREAD

**Issue by fmabid** [selim13/laravel-mix-compress#41]
Hey,
I'm getting this error! ```TypeError: Cannot read property 'tapPromise' of undefined``` while running. Did I miss something?!
Using "laravel-mix": "5.0.9"

![image](https://user-images.githubusercontent.com/20528758/214230933-001250fa-c2c7-4da2-be52-e9717f0c9bd8.png)

**Comment by selim13** [comment]
That's due to webpack version incompatibility.
mix 5.0.9 is bundled with webpack 4, while compression webpack plugin used in this module requires webpack 5

Either upgrade to mix 6 and webpack 5, or try using older compression-webpack-plugin [v6.1.1](https://github.com/webpack-contrib/compression-webpack-plugin/tree/v6.1.1), which was the last to support webpack 4, directly in your laravel mix config. Something like this:
```js
const CompressionPlugin = require('compression-webpack-plugin');

if (mix.inProduction()) {
  mix.webpackConfig({
    plugins: [
      new CompressionPlugin({
        filename: '[path].gz[query]',
        algorithm: 'gzip',
        test: /\.(js|css|html|svg|json)$/,
        minRatio: 1,
      }),
      new CompressionPlugin({
        filename: '[path].br[query]',
        algorithm: 'brotliCompress',
        test: /\.(js|css|html|svg|json)$/,
        compressionOptions: { level: 11 },
        minRatio: 1,
      }),
    ],
  });
}
```
